#!/bin/bash

# * Determine if protocol 'dccp' is really needed on this system [NETW-3200] 
# - Related resources
#     * Website: https://cisofy.com/lynis/controls/NETW-3200/

# * Determine if protocol 'sctp' is really needed on this system [NETW-3200] 
# - Related resources
#     * Website: https://cisofy.com/lynis/controls/NETW-3200/

# * Determine if protocol 'rds' is really needed on this system [NETW-3200] 
# - Related resources
#     * Website: https://cisofy.com/lynis/controls/NETW-3200/

# * Determine if protocol 'tipc' is really needed on this system [NETW-3200] 
# - Related resources
#     * Website: https://cisofy.com/lynis/controls/NETW-3200/

#!/bin/bash

# Interactive Script to Disable Unused Network Protocols
# Protocols: DCCP, SCTP, TIPC, RDS
# This improves security by reducing attack surface

# Color codes for better readability
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Error: This script must be run as root (use sudo)${NC}"
    exit 1
fi

# Define protocols to disable
PROTOCOLS=("dccp" "sctp" "tipc" "rds")
MODPROBE_DIR="/etc/modprobe.d"

# Function to prompt for continuation
prompt_continue() {
    echo -e "${YELLOW}$1${NC}"
    read -p "Continue? (y/n): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${RED}Operation cancelled by user.${NC}"
        exit 0
    fi
    echo ""
}

# Introduction
clear
echo "=========================================="
echo "  Network Protocol Security Hardening"
echo "=========================================="
echo ""
echo "This script will disable the following unused network protocols:"
echo "  • DCCP (Datagram Congestion Control Protocol)"
echo "  • SCTP (Stream Control Transmission Protocol)"
echo "  • TIPC (Transparent Inter-Process Communication)"
echo "  • RDS (Reliable Datagram Sockets)"
echo ""
echo "WHY: These protocols are rarely used in typical systems."
echo "Disabling them reduces your attack surface and improves security."
echo ""
echo "WHAT IT DOES:"
echo "  1. Backs up any existing configuration files"
echo "  2. Creates kernel module blacklist files"
echo "  3. Unloads currently loaded modules"
echo "  4. Verifies the changes"
echo ""
prompt_continue "Ready to proceed?"

# Step 1: Backup existing configuration files
echo -e "${BLUE}=========================================="
echo "STEP 1: Backing Up Existing Configurations"
echo -e "==========================================${NC}"
echo ""
echo "EXPLANATION: Before making changes, we'll back up any existing"
echo "blacklist files in the same directory (/etc/modprobe.d/)."
echo "Backups are named: [filename].bak.[timestamp]"
echo ""

backup_count=0
for proto in "${PROTOCOLS[@]}"; do
    config_file="$MODPROBE_DIR/${proto}-blacklist.conf"
    if [ -f "$config_file" ]; then
        backup_file="${config_file}.bak.$(date +%Y%m%d-%H%M%S)"
        cp "$config_file" "$backup_file"
        echo -e "  ${GREEN}✓${NC} Backed up: ${proto}-blacklist.conf"
        echo "    → $backup_file"
        backup_count=$((backup_count + 1))
    fi
done

if [ $backup_count -eq 0 ]; then
    echo "  No existing configuration files found (this is normal)."
fi
echo ""
prompt_continue "Backups complete. Continue to create blacklist files?"

# Step 2: Create blacklist configuration files
echo -e "${BLUE}=========================================="
echo "STEP 2: Creating Blacklist Configuration Files"
echo -e "==========================================${NC}"
echo ""
echo "EXPLANATION: We'll create configuration files in /etc/modprobe.d/"
echo "that tell the Linux kernel to NOT load these protocol modules."
echo ""
echo "HOW IT WORKS: When the kernel tries to load a module (e.g., 'dccp'),"
echo "it will instead run '/bin/true' which does nothing and returns success."
echo "This effectively prevents the module from loading."
echo ""

for proto in "${PROTOCOLS[@]}"; do
    config_file="$MODPROBE_DIR/${proto}-blacklist.conf"
    
    cat > "$config_file" << EOF
# Blacklist $proto protocol modules
# Generated by protocol security hardening script on $(date)
# This prevents the kernel from loading these unused network protocol modules

install $proto /bin/true
install ${proto}_ipv4 /bin/true
install ${proto}_ipv6 /bin/true
EOF
    
    echo -e "  ${GREEN}✓${NC} Created: ${proto}-blacklist.conf"
    echo "    Location: $config_file"
done
echo ""
echo "These changes will persist across reboots."
echo ""
prompt_continue "Blacklist files created. Continue to unload active modules?"

# Step 3: Unload currently loaded modules
echo -e "${BLUE}=========================================="
echo "STEP 3: Unloading Currently Active Modules"
echo -e "==========================================${NC}"
echo ""
echo "EXPLANATION: If any of these protocol modules are currently loaded"
echo "in memory, we need to unload them. The blacklist only prevents"
echo "FUTURE loading; we must manually remove any active instances."
echo ""
echo "NOTE: If a module is in use by an active connection, it cannot"
echo "be unloaded until that connection closes (or after reboot)."
echo ""

modules_found=false
for proto in "${PROTOCOLS[@]}"; do
    if lsmod | grep -q "^$proto"; then
        modules_found=true
        echo -e "  ${YELLOW}→${NC} Module '${proto}' is currently loaded, attempting to unload..."
        
        modprobe -r "$proto" 2>/dev/null
        modprobe -r "${proto}_ipv4" 2>/dev/null
        modprobe -r "${proto}_ipv6" 2>/dev/null
        
        if lsmod | grep -q "^$proto"; then
            echo -e "    ${YELLOW}⚠${NC} Warning: '${proto}' could not be unloaded (may be in use)"
            echo "    It will be disabled after the next reboot."
        else
            echo -e "    ${GREEN}✓${NC} Successfully unloaded '${proto}'"
        fi
    else
        echo -e "  ${GREEN}✓${NC} Module '${proto}' was not loaded"
    fi
done

if [ "$modules_found" = false ]; then
    echo "  No modules were loaded (excellent!)."
fi
echo ""
prompt_continue "Module unloading complete. Continue to verification?"

# Step 4: Verify protocols are disabled
echo -e "${BLUE}=========================================="
echo "STEP 4: Verification"
echo -e "==========================================${NC}"
echo ""
echo "EXPLANATION: Let's verify that none of these protocol modules"
echo "are currently loaded in the kernel."
echo ""

all_disabled=true
for proto in "${PROTOCOLS[@]}"; do
    if lsmod | grep -q "^$proto"; then
        echo -e "  ${RED}✗${NC} ${proto} is still loaded"
        all_disabled=false
    else
        echo -e "  ${GREEN}✓${NC} ${proto} is disabled"
    fi
done
echo ""

# Final Summary
echo -e "${BLUE}=========================================="
echo "FINAL SUMMARY"
echo -e "==========================================${NC}"
echo ""

if [ "$all_disabled" = true ]; then
    echo -e "${GREEN}✓ SUCCESS! All protocols are now disabled.${NC}"
    echo ""
    echo "What was done:"
    echo "  • Created blacklist configuration files in: $MODPROBE_DIR"
    echo "  • Unloaded any active protocol modules from memory"
    echo "  • Changes will persist across reboots"
    echo ""
    echo "Configuration files created:"
    for proto in "${PROTOCOLS[@]}"; do
        echo "  - ${proto}-blacklist.conf"
    done
else
    echo -e "${YELLOW}⚠ PARTIAL SUCCESS${NC}"
    echo ""
    echo "What was done:"
    echo "  • Created blacklist configuration files (protocols won't load on boot)"
    echo "  • Attempted to unload active modules"
    echo ""
    echo "Note: Some modules could not be unloaded because they're currently"
    echo "in use by active connections. The blacklist will prevent them from"
    echo "loading after reboot."
    echo ""
    echo -e "${YELLOW}RECOMMENDATION: Reboot your system to ensure all changes take effect.${NC}"
fi

echo ""
echo "Next steps:"
echo "  1. Run Lynis to verify the security improvements:"
echo "     ${GREEN}sudo lynis audit system${NC}"
echo ""
echo "  2. Review the NETW-3200 warnings - they should now be resolved"
echo ""
echo "Backup information:"
if [ $backup_count -gt 0 ]; then
    echo "  • Backup files created in: $MODPROBE_DIR"
    echo "  • Named with .bak.[timestamp] extension"
else
    echo "  • No backups were needed (no previous configurations existed)"
fi
echo ""
echo "To revert these changes:"
echo "  1. Remove the blacklist files:"
echo "     ${RED}sudo rm $MODPROBE_DIR/{dccp,sctp,tipc,rds}-blacklist.conf${NC}"
echo "  2. Reboot your system"
echo ""
echo -e "${GREEN}Security hardening complete!${NC}"
echo ""
